name: pljs Build and Test
on:
  push:
  pull_request:
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [REL_16_STABLE, REL_17_STABLE, REL_18_STABLE]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Test details
        run: echo Build and test pg_cuckoo on ${{ matrix.os }} with PostgreSQL ${{ matrix.version }} branch

      - name: Checkout and build PostgreSQL code
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config libc++-dev libc++abi-dev libglib2.0-dev libtinfo6 cmake libstdc++-12-dev
          rm -rf postgres
          git clone --branch ${{ matrix.version }} --single-branch --depth 1 https://github.com/postgres/postgres.git
          pushd postgres
          git branch
          ./configure --prefix=$PWD/inst/  --enable-cassert --enable-debug --with-openssl
          make -j4 install
          cd contrib/ltree
          make install

      - name: Start Postgres
        run: |
          pushd postgres
          cd inst/bin
          ./initdb -D data
          ./pg_ctl -D data -l logfile start
          popd

      - name: Checkout pg_cuckoo extension code
        uses: actions/checkout@v4
        with:
          path: pg_cuckoo

      - name: Build and test pg_cuckoo extension
        id: regression-tests
        run: |
          export PATH="${PWD}/postgres/inst/bin:$PATH"
          pushd pg_cuckoo
          make install
          make installcheck
          popd

      - name: Print regression.diffs if regression tests failed
        if: failure() && steps.regression-tests.outcome != 'success'
        run: |
          cat pg_cuckoo/regression.diffs
